language: java

jdk:
  - oraclejdk8
  - oraclejdk7

addons:
  postgresql: "9.3"

before_install:
  - cp etc/datasource.sample.properties etc/datasource.properties

before_script:
  - psql -c 'create database test;' -U postgres
  - psql -U postgres -c "create extension postgis"
